# Generated by Django 5.2.7 on 2026-01-30 17:12

import users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_customuser_username_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
