[tool.poetry]
name = "django-ishop"
version = "0.1.0"
description = ""
authors = ["Sergey Korobeynikov <skoro@smn35.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.7"
python-dotenv = "^1.2.1"
psycopg2-binary = "^2.9.11"
pillow = "^12.0.0"
ipython = "^9.7.0"
redis = "^7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
