# Generated by Django 5.2.7 on 2025-12-09 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
    ]
