# Generated by Django 5.2.7 on 2026-02-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(auto_now=True, verbose_name="Дата изменения"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
