# Generated by Django 5.2.7 on 2026-02-09 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_product_created_at_alter_product_updated_at"),
        ("catalog", "0009_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = []
